name: Deploy to production server
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Run npm install
          run: |
            npm ci
            npm install
            npm run lint
            npm run tsc
        - name: Generate deployment package
          run: zip -r package.zip . -x ".git/*" -x ".github/*" -x ".vscode/*"
        - name: Get timestamp
          id: timestamp
          run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')"  

        - name: Run beanstalk deploy
          uses: einaregilsson/beanstalk-deploy@v18
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: Prod-atarca-backend
            environment_name: Prod-atarcabackend-env
            region: eu-central-1
            version_label: "${{ steps.timestamp.outputs.date }}"
            deployment_package: package.zip
